-- Create bulk_requests table
CREATE TABLE IF NOT EXISTS bulk_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(50) UNIQUE NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    customer_email VARCHAR(255),
    device_count INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'Received',
    priority VARCHAR(50) DEFAULT 'Medium',
    cost DECIMAL(10, 2) DEFAULT 0,
    notes TEXT,
    admin_reply TEXT,
    technician VARCHAR(255),
    estimated_completion_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create bulk_request_devices table for individual devices
CREATE TABLE IF NOT EXISTS bulk_request_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulk_request_id BIGINT REFERENCES bulk_requests(id) ON DELETE CASCADE,
    device_number INTEGER NOT NULL,
    laptop_brand VARCHAR(100) NOT NULL,
    laptop_model VARCHAR(100) NOT NULL,
    serial_number VARCHAR(100),
    received_date DATE,
    priority VARCHAR(50) DEFAULT 'Medium',
    problem_description TEXT NOT NULL,
    device_image TEXT,
    status VARCHAR(50) DEFAULT 'Received',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_bulk_requests_customer_phone ON bulk_requests(customer_phone);
CREATE INDEX IF NOT EXISTS idx_bulk_requests_status ON bulk_requests(status);
CREATE INDEX IF NOT EXISTS idx_bulk_requests_created_at ON bulk_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_bulk_request_devices_bulk_request_id ON bulk_request_devices(bulk_request_id);

-- Enable RLS (Row Level Security)
ALTER TABLE bulk_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulk_request_devices ENABLE ROW LEVEL SECURITY;

-- Create policies for bulk_requests
CREATE POLICY "Enable read access for all users" ON bulk_requests FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON bulk_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON bulk_requests FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON bulk_requests FOR DELETE USING (true);

-- Create policies for bulk_request_devices
CREATE POLICY "Enable read access for all users" ON bulk_request_devices FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON bulk_request_devices FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON bulk_request_devices FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON bulk_request_devices FOR DELETE USING (true);
